# Generated by Django 2.0.7 on 2018-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anlz_app', '0002_auto_20180731_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
    ]
