# Generated by Django 2.0.7 on 2018-08-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anlz_app', '0003_question_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='color',
        ),
    ]
