# Generated by Django 2.0.7 on 2018-08-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anlz_app', '0004_remove_question_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_total_questions',
            field=models.IntegerField(default=10),
        ),
    ]
