# Generated by Django 2.0.7 on 2018-08-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anlz_app', '0006_auto_20180806_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenquiz',
            name='obtained_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
